import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CoffeeStore from "./coffee-store/[id]";
import Banner from './components/banner'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText = "View stores nearby" handleClick={() => console.log('Button is clicked')}/>
      </main>
    
    </div>
  );
}